variables:
  PROJECT_ID: "18700019"
  # ENV
  DEV_WEB_ENV: "https://gitlab.com/api/v4/projects/$PROJECT_ID/snippets/1991318/raw"
  # Firebase SDK
  DEV_FIREBASE: "https://gitlab.com/api/v4/projects/$PROJECT_ID/snippets/1983169/raw"
  DEV_FIREBASE_PROJECT: "myspace-dev-1ae9e"
  # Dockerimage
  NODE_IMAGE: "registry.gitlab.com/twin-intern/lampang-2020/lampang-myspace:node-firebase"
  APK_BUILD_PACKETS: "apk add --update-cache python python-dev py-pip alpine-sdk"

stages:
  - npm
  - build
  - release
  - deploy

include:
  - "/web/.gci.yml"
  - "/backoffice/.gci.yml"
